//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist_Album
    {
        public int Album_Artist_Id { get; set; }
        public int Album_Id { get; set; }
        public int Artist_Id { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Artist Artist { get; set; }
    }
}
